In [1]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.2.3

In [3]:
df = pd.read_csv(r'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
# dataframe shape
print(df.shape)

(10000, 11)

In [5]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [6]:
# checking for missing variables
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df.fuel_efficiency_mpg.max()

41.2

In [8]:
df.horsepower.median()

254.0

In [9]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [16]:
df['horsepower'] = df['horsepower'].fillna(252)

In [17]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [18]:
df.horsepower.median()

252.0

In [28]:
df_1 = df.loc[df['origin'] == 'Asia',['vehicle_weight','model_year']]

In [29]:
df_1 = df_1.head(7)

In [30]:
df_1

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [31]:
x = df_1.to_numpy()

In [32]:
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [33]:
xT = x.transpose()

In [34]:
XTX = np.dot(xT,x)

In [35]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [36]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [37]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [38]:
a = np.dot(XTX_inv,xT)

In [39]:
w = np.dot(a,y)

In [40]:
w

array([0.13644777, 0.2327492 ])

In [41]:
w.sum()

np.float64(0.3691969690492638)